# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: check-ast
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-merge-conflict
        -   id: check-case-conflict
        -   id: check-json
        -   id: check-yaml
        -   id: check-toml
        -   id: check-added-large-files
        -   id: detect-private-key

    -   repo: https://github.com/psf/black
        rev: 22.12.0
        hooks:
        -   id: black
            args: [--line-length=79]

    -   repo: https://github.com/pycqa/flake8
        rev: 6.0.0
        hooks:
        -   id: flake8
            additional_dependencies: [
                'pep8-naming==0.13.3',
                # 'flake8-isort==6.0.0',
                'flake8-print==3.1.4',
                # 'flake8-builtins==2.1.0',
                'flake8-bugbear==23.1.20',
                'flake8-simplify==0.19.3',
                'flake8-fastapi==0.7.0',
                'flake8-async==22.11.14',
                # 'flake8-docstrings==1.7.0',
                'flake8-implicit-str-concat==0.3.0',
            ]
            args: ['--extend-exclude=*/__init__.py,*/migrations*']
