FROM python:3.10-slim
WORKDIR /src
ENV PYTHONPATH=/app

RUN mkdir /xls
VOLUME [ "/xls" ]

COPY requirements.txt alembic.ini ./
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt
COPY requirements-dev.txt ./
RUN pip install --no-cache-dir --upgrade -r ./requirements-dev.txt

COPY app/ ./app
COPY tests/ ./tests
